services:

  postgres:
    image: postgres
    expose:
      - "5432"
    environment:
      POSTGRES_PASSWORD: admin
    volumes:
      - mypsql-data:/dev/shm
      - ./schema:/docker-entrypoint-initdb.d
    restart: always

  app:
    container_name: todo-api
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres

volumes:
  mypsql-data: